### ISSUE TITLE
How can I hide "Posted by [name] on [date]" and "Posted in [category]"  from my posts? 

### ISSUE THREAD

**Issue by kaeelgie** [dflippo/UU2014#37]
I'd like to make our website look less like a blog by removing the author, date and post category from entries.
I've read some suggestions in WordPress Forums, which involve creating custom .css and/or creating a child theme.  But I don't understand them.  Can you help me out? Maybe there is a "teaching" page I could read?
www.aconwr.ca  is my website

**Comment by dflippo** [comment]
In coming up with the answer to your question, I found a bug with the theme's feature to hide by-lines (author) from posts.  I fixed that and since I was already editing it, I added the ability to hide posted-on dates, post-formats, categories, and tags on posts.

It will take a little while for this to be published automatically through WordPress.org so I recommend that you delete your copy of the theme and manually download / upload this version:
https://github.com/dflippo/UU2014/releases/download/1.3.8/uu-2014.1.3.8.zip

After you delete the version of the theme that you have, you can manually upload a theme by going to Appearance -> Themes, the "Add New" button at the top of the page and then the "Upload Theme" button at the top of the page.

Once you have the new version, removing these sections is easy.  Go to Appearance -> Customize -> "UU2014 - Display and Hide Features" and turn off bylines, posted-on dates, post formats, categories, and tags.

**Comment by dflippo** [comment]
I just submitted version 1.3.8 to WordPress.org and you can also download the new version from there:
https://wordpress.org/themes/download/uu-2014.1.3.8.zip

It won't automatically be pushed down to every user until someone on the theme review team can take a look and ensure I haven't committed any WordPress.org sins.  I'm sure it will pass but it might take a couple days.

**Comment by kaeelgie** [comment]
Thank you so much for doing this, and so quickly.WordPress has already loaded the update, and I downloaded it.
But now I have a new problem.Now the following categories appear below the Menu in the sidebar.   
   - Recent Posts   

   - Archives   

   - Categories.   

They weren't there before. 
How did I hide them before?  I can't find a way to do this.
I do want a side menu to display, but not those "things" (whatever they are properly called) below. Kae Elgie

**Comment by dflippo** [comment]
To hide the default content you just need at least one widget in the sidebar.  You can put an empty text widget initially.  To hide the navigation menu, you can create an empty menu.  Then in the next tab, you can assign the second navigation area to this empty menu.  Alternately, you can disable the sidebar if you don't plan to use it.  That is in the customizer.

**Comment by kaeelgie** [comment]
I'm trying to figure out what a widget is, and what an empty text widget is. I'll keep looking. Or maybe a friend can help me translate. Sorry for being so out if it. ‎I'm in over my head.                                                                                                                                                                                                                                                                          Kae Elgie                                                                                                                                                                                                                                          From: Dan FlippoSent: Thursday, January 22, 2015 11:22 PMTo: dflippo/UU2014Reply To: dflippo/UU2014Cc: kaeelgieSubject: Re: [UU2014] How can I hide "Posted by [name] on [date]" and "Posted in [category]"  from my posts?  (#37)To hide the default content you just need at least one widget in the sidebar.  You can put an empty text widget initially.  To hide the navigation menu, you can create an empty menu.  Then in the next tab, you can assign the second navigation area to this empty menu.  Alternately, you can disable the sidebar if you don't plan to use it.  That is in the customizer.

—Reply to this email directly or view it on GitHub.
