### ISSUE TITLE
Child Theme 

### ISSUE THREAD

**Issue by Willowcase** [dflippo/UU2014#40]
I didn't want to intrude on your dialogue with Marty. I use the import method because I can't figure out the enqueue method. Dan, I was wondering if it would be too much trouble to offer for download a basic child theme folder with files set up in the proper manner, for those that would like to use one? Your theme is excellent and doesn't need much customizing, but for those of us that like to play with css and have other needs, it is quite helpful.  Many of us can handle css edits, but are not comfortable with php. I had no idea there would be two calls and it is not evident from the WP codex instructions for doing the enqueue method. I think all themes should come with a basic child theme.
Would using the import method instead of the enqueue method be why some of my custom css in my child theme won't override the parent?
Thanks Dan, I finally signed up to post on this forum instead of WP. Your update fixed the issue with the gallery. Thank you for your time and talent.

**Comment by dflippo** [comment]
This was a busy work week so I am behind on responding to issues.  I think your suggestion has merit.  However, for most needs, I recommend either using the Jetpack plugin's Custom CSS feature or style/script tags in a footer widget to customize the theme.  Tonight I was at a WordPress meetup and that is exactly what several of the professional WP designers use for their clients.  Both allow you to change a lot of things, aren't wiped out by updates, and don't require you to learn PHP.  I will try to get to the child theme in the next couple weeks.

**Comment by Willowcase** [comment]
Thanks very much Dan. That will be most helpful. Jetpack is too much for my needs, nor do I want to connect with wordpress.com. However, it is a very good plugin for many people's needs. I am volunteering to do this for another person and teaching her as I go (for her to manage and I will help her anytime after I am finished). Don't want to overwhelm her with too many gizmos. ;-)  
Thanks again for your time and talent.

**Comment by dflippo** [comment]
I understand. Have you tried the footer text widget approach?  That is what I use to add JavaScript to my main site, KentUU.org.  Even though I have Jetpack activated, I try to disactivate as many modules as possible and use core WP features.  As long as your just need JS or CSS, putting it in a text widget is the path of least resistance.  I have a post over on UUWP.org on JS to change the header image but CSS should work just as well.

**Comment by Willowcase** [comment]
Thanks. I have no problem doing css and other things in my child theme, can even do a tad of php with clear instruction. I just couldn't (or to afraid) to make the new WordPress non import enqueue method to make the child theme. Was just wanting to have a pre-made one (see how it was done to make any future children) and reset up my current child that way using it. I am currently using the import method for my child theme and it works. Just would like to do the new method but couldn't accomplish that. I didn't know you could put javascript in a footer text widget to change something somewhere else like the header. Isn't there a header widget available also to put it in or am I missing something? Thanks.

**Comment by IgnitionMetalArtDesign** [comment]
Hi Willow
Not to intrude but wanted to share what I learned about using scripts in the footer  First I had never heard of doing that to modify a site  until Dan mentioned it    I too have been struggling with enque vs import to develop a child theme     Turns out that using scripts in the footer is a popular method for mods to  a site   What an epiphany ! :)   Anyway if you Google the search terms "footer script load faster" or similiar  searches on the subject there is  some interesting info   The enque method for child theme development loads faster than the import method so it is desirable.  So hopefully we will eventually have  an enque child theme frame for UU2014 but in the meanwhile......I can get my head around learning script writing easier than trying to master enque LOL
Marty

**Comment by Willowcase** [comment]
Thanks Marty. lol I will give it a shot. May be fun. I like to do stuff myself instead of relying on plugins for every little thing. I teeter between tech and forgetting my name.
Willow

**Comment by dflippo** [comment]
The reason that people use the footer is because CSS is applied sequentially and the last CSS will usually win unless the original CSS is flagged with !important.  I only use that in a couple places so you shouldn't have trouble applying changes to the CSS.  I haven't forgotten the child theme but had a scout camping trip last weekend and I am traveling this week for work.  I just have to fit it into the schedule.

**Comment by Willowcase** [comment]
Thanks for the information. Thanks for your time.

**Comment by dflippo** [comment]
All,

I have published an example child theme at https://github.com/dflippo/uu2014-child
You can download the zip from:
https://github.com/dflippo/uu2014-child/archive/master.zip

I tested it on my own development server and it worked without any issues using the enqueue method for syles and JavaScript.  Let me know if you have any problems.

Dan

**Comment by Willowcase** [comment]
Thank you.
