### ISSUE TITLE
Customiser fault...

### ISSUE THREAD

**Issue by dzamelt** [dflippo/UU2014#41]
Dear Amazing Theme Designer,

The customiser worked okay on a different site, but when I applied it to my main site, the customer options are not displayed. I updated with all the recommended plugins, although I had to install them manually as the auto option was not following through.

Does anyone have any idea why the customiser is not working? And whether there is an alternative way than using the customiser... it doesn't seem so.

Many thanks

Dza

**Comment by dflippo** [comment]
First try deleting the theme from your site and then installing from within Wordpress (not by uploading zip).  I have seen odd things when people started with  zip from Github.  Second, you should also consider reinstalling Wordpress which sounds worse than it is because there is a button to do this on the updates screen.  Third, try disabling all of the plugin's on your site and see if you get the customizer.  If you do, enable your plugins one at a time to identify the culprit.  There aren't many ways for the theme's screens to stop appearing because it is using core Wordpress functions to display the screens.  As long as you have a complete set of theme files (first fix) and a complete, up to date Wordpress install (second fix), then it must be a plugin causing the problem (third fix).

**Comment by dzamelt** [comment]
Thank you for this information, I started back to front and disabled a few plugins which it turns out was the issue. I think it was a petition plugin and may be that one of the petitions had expired which had caused some probs on a previous Zion theme - if wasn't that in, it could have been the revolving earth plugin - will know for sure in good time - so didn't need to reinstall etc.

Okay Great theme, spot on - hopefully will donate when we start to generate some income etc. Thanks.
