### ISSUE TITLE
UU2014 & W3C Validator Errors

### ISSUE THREAD

**Issue by ametsot** [dflippo/UU2014#50]
Hello

First of all I would like to tell you that you have create a great theme and it is really helpful to me.

I would like to validate my page with W3C-CSS validator (https://jigsaw.w3.org/css-validator/). 

Unfortunately, i take errors and i don't know how to fix it. 

Location: 
•	/wp-content/themes/uu-2014/style.css?ver=20150115

Error 1: 
•	text-rendering: auto;
•	Property text-rendering doesn't exist : auto 

Error 2:
•	button.menu-toggle
•	Value Error : background-image gradient(radial,60% 0,100,60% 0,0,from(rgba(255, 255, 255, 0)),to(rgba(255, 255, 255, 0.25))) is not a background-image value : gradient(radial,60% 0,100,60% 0,0,from(rgba(255, 255, 255, 0)),to(rgba(255, 255, 255, 0.25))) 

Error 3:
•	.panel-row-style-cell-borders .widget_origin_list
•	Property zoom doesn't exist : 1 

I would appreciate any help. Thanks again.

Ever grateful

**Comment by dflippo** [comment]
There are selectors and properties that I use in the style.css that are not part of the W3C standard because there is varying support for the official tags.  I try to support a variety of browser vendors and versions so I have some vendor specific tags but I also make an attempt to always have the official W3C selector/attribute last so it takes precedence.  Every web browser is designed to skip over the CSS selectors/tags that it doesn't understand so I don't think this will cause you any issues.  The more important validation for websites is for the HTML.  The theme is developed for HTML5 and I believe the theme will validate against that standard.

Your alternative would be to create a child theme with your own valid CSS and not enqueue the CSS from the parent theme.  That isn't my suggestion but it is an option.
