### ISSUE TITLE
Why would the favicon.ico not appear (when checked to display) in the latest version of UU-2014.  Does this have anything to do with using the Meteor slides plugin as a header widget?  I have created my own favicon.ico but no favicon appears for the site.

### ISSUE THREAD

**Issue by hdvtwin** [dflippo/UU2014#55]

**Comment by dflippo** [comment]
The theme customizer allows you to turn on or off the favicon.ico feature.  For replacing the favicon.ico, the easiest approach is to keep the theme's feature off and then upload your favicon.ico file to the root folder of your website.  That is where web browsers expect the file to be and that is also why the theme has this feature turned off by default - it allows your image to be used instead of the theme.  You would have to use a FTP program to upload the file, WordPress can't upload files to to the root folder.  Let me know if this is enough information or if you need more information on where to put the image.
