### ISSUE TITLE
How do I change the suggested headers - Found out how..disregard

### ISSUE THREAD

**Issue by kjonestennk12** [dflippo/UU2014#57]
I'd like to use the randomize headers. However, I have my own "suggested" headers I would like to use instead of the templates. How do I change out what is there to what I want? Thanks in advance for your help.

**Comment by dflippo** [comment]
There are two ways.  First, you could create a child theme and change the
images but that is not my suggestion.  The theme supports putting a
slideshow widget in the header.  There are many plugins that will give you
a lot of control and this tends to work better than the core WordPress
feature.  I use this ability on the kentuu.org website as an example.  If
you want a recommendation, I like the free Cyclone Slider 2 plugin because
it works well on mobiles, is responsive, and elsewhere on your site,
sliders can include YouTube and Vimeo videos.  Free slideshow plugins
usually leave out video to entice you to buy the paid version.
