### ISSUE TITLE
Paragraph display in visual editor

### ISSUE THREAD

**Issue by SScott-UUCC** [dflippo/UU2014#62]
There seems to have been a change when UU2014 was most recently updated that affects how paragraphs display in the visual editor. Previously, pressing the ENTER key in the visual editor created a new paragraph with a visible blank line between the new paragraph and the previous one. Now, pressing the ENTER key creates a new paragraph, but without the visible blank line. I find the new behavior very frustrating because I cannot tell at a glance in the visual editor whether there is a paragraph-end or simply a line-break between lines. To deal with the problem, I have had to turn off the TinyMCE feature that strips <p> and <br> codes from the text editor and then switch to the text editor to determine if a particular line ends with a </p> or a <br /), which takes much more time.

I would hope whatever change was made that affects paragraph display in the visual editor could be reversed in a new update RSN (real soon now). Thanks!

**Comment by dflippo** [comment]
Scott,

I haven't released a new version of the theme since January.  I have the latest version of the theme on uuwp.org and I couldn't reproduce your issue.  When I tried creating three paragraphs with a single [Enter] at the end of each line, I saw the following:
![image](https://cloud.githubusercontent.com/assets/5725557/7339908/eceac64c-ec4c-11e4-8f11-cfaf68876ec3.png)

Assuming the screen above is what you were hoping to see, could you have a plugin that is interfering with the theme?  

I am about to release a new version of the theme completely unrelated to your issue but I saw the same under that future version.

Dan

**Comment by SScott-UUCC** [comment]
Hello, Dan,

 

Thanks so much for your response! Yes, the screen-shot you sent is what I’d like to be seeing, but I’m not getting that extra blank line between paragraphs any more in the visual editor.

 

I’m the webmaster for the UU Church of Columbia, Missouri. I started working last November on converting our current static HTML site at http://uuchurch.net to a Wordpress site using the UU2014 theme. However, I wasn’t able to continue working on the Wordpress site after sometime in January – before you released the theme update – because I got too busy leading our stewardship campaign.

 

I only noticed the January update to UU2014 last week when I started working again on the Wordpress site. Of course, as it had been several months since I last worked on the Wordpress site, a number of plugins wanted to be updated when I re-started, so it would be hard to say if a specific plugin is causing the issue. I’ve sorta gotten used to the problem and can live with it for now. When I have time, I may try deactivating various plugins to see if one of them is causing the issue.

 

BTW, your January theme update threw me for a loop at first with the new menu in the sidebar. We have a very complex site with more than 100 pages, so that menu is not suitable for our site. I managed to “turn it off” by creating a new blank menu for the sidebar. We want only a few key links in the sidebar that go to the most important pages.

 

When I launch the new Wordpress site in another month or so, I’m going to want to change the text in the footer. What is the easiest, permanent way to do that (one that will not be affected by future theme updates)?

 

Thanks again for your response.

 

Steve Scott, Webmaster

UU Church of Columbia, Missouri

c/o Scott Law Firm, P.C.

201 Westwood Ave.

Columbia, MO 65203-2871

Phone: 573-442-7268

Fax: 573-443-1676

sscott@scottlawfirm.com

**Comment by dflippo** [comment]
Steve,

The recommendation on the footer is to add a text widget to the footer's
widget area and to leave the current text at the very bottom.  You can see
that on the Kentuu.org website once you know what to look for.  The text
you would be leaving is the name of your site, a link with the name of the
theme, and a login link.  That login link is there to make it easier for
less technical users to figure out how to login.  I have received positive
feedback on that feature in district and congregational training sessions.
A couple websites created a child theme to take it out because they
perceived it as a security issue but bots already know the login URL for
Wordpress so I would disagree.

In general, if you want to change any of the out of the box theme features,
you would want to create a child theme.  I have put a starter child theme
here on Github and you can add newer versions of any of the php files to
your copy to override the default code.  This allows you to run future
updates of the parent theme without losing any of your changes.  Adding
widgets to your page is easier and will also not be lost when you run theme
updates.

Good luck,

Dan Flippo
UU Church of Kent Ohio

On Sunday, April 26, 2015, SScott-UUCC <notifications@github.com> wrote:

> Hello, Dan,
>
>
>
> Thanks so much for your response! Yes, the screen-shot you sent is what
> I’d like to be seeing, but I’m not getting that extra blank line between
> paragraphs any more in the visual editor.
>
>
>
> I’m the webmaster for the UU Church of Columbia, Missouri. I started
> working last November on converting our current static HTML site at
> http://uuchurch.net to a Wordpress site using the UU2014 theme. However,
> I wasn’t able to continue working on the Wordpress site after sometime in
> January – before you released the theme update – because I got too busy
> leading our stewardship campaign.
>
>
>
> I only noticed the January update to UU2014 last week when I started
> working again on the Wordpress site. Of course, as it had been several
> months since I last worked on the Wordpress site, a number of plugins
> wanted to be updated when I re-started, so it would be hard to say if a
> specific plugin is causing the issue. I’ve sorta gotten used to the problem
> and can live with it for now. When I have time, I may try deactivating
> various plugins to see if one of them is causing the issue.
>
>
>
> BTW, your January theme update threw me for a loop at first with the new
> menu in the sidebar. We have a very complex site with more than 100 pages,
> so that menu is not suitable for our site. I managed to “turn it off” by
> creating a new blank menu for the sidebar. We want only a few key links in
> the sidebar that go to the most important pages.
>
>
>
> When I launch the new Wordpress site in another month or so, I’m going to
> want to change the text in the footer. What is the easiest, permanent way
> to do that (one that will not be affected by future theme updates)?
>
>
>
> Thanks again for your response.
>
>
>
> Steve Scott, Webmaster
>
> UU Church of Columbia, Missouri
>
> c/o Scott Law Firm, P.C.
>
> 201 Westwood Ave.
>
> Columbia, MO 65203-2871
>
> Phone: 573-442-7268
>
> Fax: 573-443-1676
>
> sscott@scottlawfirm.com
> <javascript:_e(%7B%7D,'cvml','sscott@scottlawfirm.com');>
>
>
>
> From: Dan Flippo [mailto:notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>]
> Sent: Sunday, April 26, 2015 6:51 PM
> To: dflippo/UU2014
> Cc: SScott-UUCC
> Subject: Re: [UU2014] Paragraph display in visual editor (#62)
>
>
>
> Scott,
>
> I haven't released a new version of the theme since January. I have the
> latest version of the theme on uuwp.org and I couldn't reproduce your
> issue. When I tried creating three paragraphs with a single [Enter] at the
> end of each line, I saw the following:
> <
> https://cloud.githubusercontent.com/assets/5725557/7339908/eceac64c-ec4c-11e4-8f11-cfaf68876ec3.png>
> image
>
> Assuming the screen above is what you were hoping to see, could you have a
> plugin that is interfering with the theme?
>
> I am about to release a new version of the theme completely unrelated to
> your issue but I saw the same under that future version.
>
> Dan
>
> —
> Reply to this email directly or view it on GitHub <
> https://github.com/dflippo/UU2014/issues/62#issuecomment-96449043> . <
> https://github.com/notifications/beacon/ALgw1eOn1VPxrdZ6CQnKbt8MSgzVz6BZks5oDXGBgaJpZM4EGMzR.gif>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dflippo/UU2014/issues/62#issuecomment-96455104>.
>


-- 
Dan Flippo
Mobile - (330) 990-4811
Personal email - djf13@cornell.edu
