### ISSUE TITLE
Problem with UU 2014 on Ipad image portrait.

### ISSUE THREAD

**Issue by jmvillemaire** [dflippo/UU2014#76]
When I change the orientation of the ipad from landscape to portrait , the image don't adapt very well.
Is somebody have an idea ??
You may see the effect on the site :http://malala.connexence.com:8083/
Thanks
jmv

**Comment by dflippo** [comment]
It is happening because I have CSS that prevents the header image from becoming less than 120px:

```
@media screen and (max-width: 782px)
.header-widget-area > img {
    min-height: 120px;
}
```

With your 1500px x 249px header image, you can fix the issue by adding this to a text widget:

```
<style>
@media screen and (max-width: 782px)
.header-widget-area > img {
    min-width: 750px;
}
</style>
```

This will cause your image to stop shrinking when it is half of it's full width.  At that point, part of the image will begin to overflow past the right side of your page.

**Comment by jmvillemaire** [comment]
Good Morning,
Thank you very much for the answer . I will certainly try that and I will email you back if the problem is fixed. 
For the moment , I have to go to work.
Have a nice we .
Best wishes.
Jean-Marc Villemaire md

**Comment by jmvillemaire** [comment]
Hello, 
I tried your patch , but It seems that there is no effect on the portrait image on Ipad .
May be it’s me . Do you have other idea?
Thanks anyway for your time and help.
Have a good day.
Jean-Marc Villemaire

**Comment by jmvillemaire** [comment]
Hi again,
Finally , I found a trick to fix the problem .
Thank you for your time .
Jean-Marc Villemaire
